services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
    db:
        container_name: blog-db
        image: postgres:16.0
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8001:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "8080:80"
        depends_on:
            - db
volumes:
    db_data:
